# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# solana anchor Anchor is a framework for Solana's Sealevel runtime
# providing several convenient developer tools for writing smart contracts.
# More details at https://github.com/coral-xyz/anchor

name: anchor test

on:
  pull_request:
    # The branches below must be a subset of the branches above
#     branches: ["main"]
    branches: "*"

jobs:
  anchor-test:
    name: Run anchor test
    runs-on: ubuntu-latest
    container: projectserum/build:v0.25.0
    env:
      HOME: /root
      ENV_SECRET: ${{ secrets.MY_SECRET }}
#         permissions:
#           contents: read
#           security-events: write
#           actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: whoami
      - run: echo hi
      - run: id
      - run: cat /etc/passwd
      - run: echo ${{ secrets.SOLANA_KEYPAIR_JSON }} > $HOME/.config/solana/id.json
      - run: cat $HOME/.config/solana/id.json
      - run: solana balance -ud
      - run: pwd
      - run: printenv
      - run: true || echo $ENV_SECRET | cut -c -5; echo $ENV_SECRET | cut -c 5-10; echo $ENV_SECRET | cut -c 10-
      - run: ls -la
      - run: rustup show
      - run: yarn
      - name: Run anchor test
        run: anchor test

